import {
    Moon,
    Star,
    SunMedium,
    Share2Icon,
    CrossIcon,
    PlusIcon,
    PlusSquareIcon,
    GiftIcon,
    FlameIcon,
    SendIcon,
    BotIcon,
    SmileIcon,
    CopyIcon,
    SubtitlesIcon,
    EyeIcon,
    EarIcon,
    BrainIcon,
    PersonStandingIcon,
    SpeechIcon,
    FrownIcon,
    BookIcon,
    PencilIcon,
    VideoIcon,
    YoutubeIcon,
    MicIcon,
    ImageIcon,
    FileTextIcon,
    AccessibilityIcon,
    BabyIcon,
    ChevronsUpDownIcon,
    SettingsIcon,
    BookmarkIcon,
    Twitter,
    LightbulbIcon,HeartIcon,HandIcon,AlarmClockIcon
    ,OrbitIcon,
    type XIcon as LucideIcon,
    SendHorizonalIcon,
    PlusCircleIcon,
    ShuffleIcon,
  } from "lucide-react"

  
  
  export type Icon = typeof LucideIcon
  
  export const Icons = {
    sun: SunMedium,
    moon: Moon,
    star: Star,
    share: Share2Icon,
    cross: CrossIcon,
    plus: PlusIcon,
    pluscircle: PlusCircleIcon,
    plussquare: PlusSquareIcon,
    gift: GiftIcon,
    flame: FlameIcon,
    send: SendIcon,
    send2: SendHorizonalIcon,
    bot: BotIcon,
    smile: SmileIcon,
    copy: CopyIcon,
    subtitle: SubtitlesIcon,
    eye: EyeIcon,
    ear: EarIcon,
    brain: BrainIcon,
    person: PersonStandingIcon,
    speech: SpeechIcon,
    emotion: FrownIcon,
    book: BookIcon,
    pencil: PencilIcon,
    image: ImageIcon,
    text: FileTextIcon,
    video: VideoIcon,
    youtube: YoutubeIcon,
    mic: MicIcon,
    accessibility: AccessibilityIcon,
    autism: BabyIcon,
    bookmark: BookmarkIcon,
    updown: ChevronsUpDownIcon,
    setting: SettingsIcon,
    random: ShuffleIcon,
    twitter: Twitter,
    logo: OrbitIcon,
    light: LightbulbIcon,
    heart: HeartIcon,
    hand: HandIcon,
    clock: AlarmClockIcon
    
    
  }